settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: workers-cloudflare-com # unique identifier
    name: workers.cloudflare.com
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://workers.cloudflare.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: www-cloudflare-com
    name: www.cloudflare.com
    description: 'Built for anything connected to the Internet.'
    url: 'https://www.cloudflare.com'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: lowyat-net
    name: Lowyat NET
    url: 'https://www.lowyat.net/'
    method: GET
    expectStatus: 200

  - id: forum-lowyat-net
    name: Lowyat Forums
    url: 'https://forum.lowyat.net/'
    method: GET
    expectStatus: 200

  - id: hype-my
    name: Hype MY
    url: 'https://hype.my/'
    method: GET
    expectStatus: 200

  - id: murai-my
    name: Murai MY
    url: 'https://murai.my/'
    method: GET
    expectStatus: 200

    - id: lipstiq-com
    name: Lipstiq
    url: 'https://lipstiq.com/'
    method: GET
    expectStatus: 200

  - id: varnam-my
    name: Varnam MY
    url: 'https://varnam.my/'
    method: GET
    expectStatus: 200

  - id: diva-my
    name: Diva MY
    url: 'https://diva.my/'
    method: GET
    expectStatus: 200

  - id: fourthofficial-com
    name: Fourthofficial
    url: 'https://fourthofficial.com/'
    method: GET
    expectStatus: 200
